# Generated by Django 3.1.5 on 2021-01-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='dronePorte',
            new_name='dronePorteInicial',
        ),
        migrations.AddField(
            model_name='rota',
            name='dronePorteFinal',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
